apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: "registry.cn-hangzhou.aliyuncs.com/clouddevs/kanico:latest"
      #imagePullPolicy: IfNotPresent
      #   stdin: false
      #stdinOnce: true
      args:
        - '--dockerfile=Dockerfile'
        - '--context=git://github.com/loyurs/qkrun.git#refs/heads/master'
        - '--destination=ccr.ccs.tencentyun.com/tctd/k8k8:latest'
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
